<?php include 'Mensagem.php'; ?>

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
			<title>Livro de Visitas</title>

			<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>

			<script type="text/javascript">
				$(function(){

					//Script executado no clique do botão
					$('.btn').click(function(){
			
						//Guarda os dados necessários em variaveis
						var email = $('#email').val();
						var site = $('#site').val();
						var nome = $('#nome').val();
						var msg = $('#msg').val();
						
						//Chama 'cadastra.php', limpa os valores dos campos mensagem, nome, email e site,
						//e por ultimo chama 'atualiza.php'.
						$.post('cadastraMensagem.php', {
							
							nome_post: nome,
							msg_post: msg,
							email_post : email,
							site_post : site,
							
						}, function(res_cadastra){			
							$('textarea[name=mensagem]').val('');
							$('input[name=nome]').val('');
							$('input[name=email]').val('');
							$('input[name=site]').val('');
							
							$.post('atualiza.php', function(atualiza_comentarios){			
								$("#comentarios ul").html(atualiza_comentarios);			
							});
										
						});
				
						return false;	
				
					});
			
				})
			</script>

		</head>

		<!-- Escolhe o cabeçalho levando em consideração se o usuario esta logado ou não.-->
		<body>
			{if $logado == 0}
				<a href='login.phtml'>Login</a><br />
				<a href='cadastro.phtml'>Cadastrar</a><br /><br />
			{else}
				Seja bem-vindo {$nome} ! <br /><br />
				<a href='logout.php'>Logout</a><br /><br />
			{/if}

			<!-- Formulario para entrada dos dados.-->
			<div id="formulario">
				<form name="enviaComentarios" method="post" action="" enctype="multipart/form-data">        
					<div class="inputs">
						<!-- Caso não haja usuario logado, pede nome, email e website.-->
						{if $logado == 0}
							Nome: <input type="text" name="nome" id="nome" /><br /><br />
							E-mail: <input type="text" name="email" id="email" /><br /><br />
							Website: <input type="text" name="site" id="site" /><br /><br />
						{/if}
						Comentario: <br /><textarea name="mensagem" id="msg" rows="10" cols="100" ></textarea>
					</div>
					<input type="submit" name="enviar" value="Enviar" class="btn" />
				</form>
			</div>
			<div id="box">
				<!-- Parte para mostrar os comentarios.-->
				<div id="comentarios">
					<h1>Livro de Visitas</h1>
						<ul>
							<!-- Caso não haja comentarios, mostra a mensagem correspondente.-->
							{if $contarComentarios == 0}
								<li><strong>[ Sistema do site - Em " . {date('d/m/Y')} ." ] </strong> Disse:
									<span>Nenhum comentário até o presente momento. Seja o primeiro a comentar!!! </span>
								</li>	
								<!-- Se houver comentarios, exibe cada um.-->
								{else}
									{foreach $comentarios as $infoComentario}
										<li><strong>[ {$infoComentario->getNome()} - Em "  {$infoComentario->getData()} " ] </strong> Disse:
										<span> {$infoComentario->getMsg()} </span>
										</li> 
									{/foreach}
							{/if}
						</ul>    
				</div>    
			</div>
	</body>
</html>